# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
