# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-12 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_passage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
