# Generated by Django 2.2 on 2019-11-20 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='正文内容')),
                ('background_img', models.CharField(max_length=2000, verbose_name='文章背景图片')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('post_time', models.DateTimeField(verbose_name='发布时间')),
                ('is_draft', models.BooleanField(default=True, verbose_name='是否为草稿')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
