# Generated by Django 2.2.4 on 2019-11-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='title',
            field=models.CharField(default='title', max_length=100, verbose_name='标题'),
        ),
    ]
