# Generated by Django 3.0.2 on 2020-01-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0004_passage_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='user',
        ),
    ]
